#!/bin/python3
# https://www.hackerrank.com/challenges/coin-change/problem

import sys

def getWays(n, c):
    # Complete this function
    m = len(c)
    if m == 0:
        return 0
    dp = [[0 if i%c[0] else 1 for i in range(n+1)] for j in range(m)]
    for i in range(1,m):
        for j in range(n+1):
            dp[i][j] = dp[i-1][j]
            if c[i] <= j:
                dp[i][j] += dp[i][j-c[i]]
            
    return dp[m-1][n]
        
n, m = input().strip().split(' ')
n, m = [int(n), int(m)]
c = list(map(int, input().strip().split(' ')))
# Print the number of ways of making change for 'n' units using coins having the values given by 'c'
ways = getWays(n, c)
print(ways)
